apiVersion: v1
kind: Service
metadata:
  name: chargingservice-service
spec:
  selector:
    app: chargingservice
  ports:
    - protocol: TCP
      port: 31004
      nodePort: 30004 # Port to access the service outside the cluste
      targetPort: 8080  # Port your application is listening on inside the pods
  type: NodePort      # Set the Service type to NodePort