apiVersion: apps/v1
kind: Deployment
metadata:
  name: chargingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chargingservice
  template:
    metadata:
      labels:
        app: chargingservice
    spec:
      containers:
        - name: chargingservice
          image: tschissler/chargingservice:latest
          ports:
            - containerPort: 8080