apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvservice
  template:
    metadata:
      labels:
        app: pvservice
    spec:
      containers:
        - name: pvservice
          image: tschissler/pvservice:latest
          env:
            - name: PowerDogPassword
              value: init