apiVersion: v1
kind: Service
metadata:
  name: pvservice-service
spec:
  selector:
    app: pvservice
  ports:
    - protocol: TCP
      port: 31003
      nodePort: 30003 # Port to access the service outside the cluste
      #targetPort: 5003  # Port your application is listening on inside the pods
  type: NodePort      # Set the Service type to NodePort