name: TestService Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3

    - name: Build and publish Docker image
      env:
        PACKAGE_VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        # Get the package version from your package.json or equivalent file.
        PACKAGE_VERSION=$(cat package.json | jq -r .version)
        
        # Build the Docker image with the package version tag.
        docker build -t tschissler/testservice:${PACKAGE_VERSION} -t tschissler/testservice:latest -f ./TestService/Dockerfile --push .
