name: TestService Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file TestService/Dockerfile --tag tschissler/testservice:$(date +%s)
