name: TestService Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3
        
    - name: Build and publish Docker image
      run: |        
        # Build the Docker image with the package version tag.
        docker build -t tschissler/testservice:${{ github.sha }} -t tschissler/testservice:latest -f ./TestService/Dockerfile --push .

    - name: Update Kubernetes deployment
      run: |
        microk8s kubectl set image deployments/testservice testservice=tschissler/testservice:${{ github.sha }}
