name: TestService Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3
        
    - name: Build and publish Docker image
      run: |        
        # Build the Docker image with the package version tag.
        docker build -t tschissler/testservice:${{ github.sha }} -t tschissler/testservice:latest -f ./TestService/Dockerfile --push .
    
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

    - name: Update Kubernetes deployment
      run: |
        kubectl set tschissler/testservice your-testservice=tschissler/testservice:${{ steps.bump.outputs.newTag }}
    - name: Deploy to Kubernetes
      run: microk8s kubectl apply -f /home/thomasschissler/SmartHome/deploy.yaml
