name: Build SmartHome.Web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      solution: 'SmartHome.Web.sln'
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solution }} -r linux-arm
    - name: Build
      run: dotnet publish ${{ env.solution }} --no-restore -r linux-arm 
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    
    
    - uses: actions/upload-artifact@master
      with:
        name: SmartHome.Web.artifacts
        path: |
          PVService/bin/Debug/net6.0/linux-arm/publish
          ChargingService/bin/Debug/net6.0/linux-arm/publish
          Smarthome.Web/bin/Debug/net6.0/linux-arm/publish
  
  deploy:
    runs-on: [self-hosted]
    needs: build
    
    steps:
    - name: Removing old content
      run: |
        rm -rf ~/SmartHome/Smarthome.Web
        rm -rf ~/SmartHome/PVService
        rm -rf ~/SmartHome/ChargingController
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: SmartHome.Web.artifacts
        path: ~/SmartHome
        
    - name: Start PV Service
      run: |
        chmod +x ~/SmartHome/PVService/bin/Debug/net6.0/linux-arm/publish/PVService
        lxterminal -e 'cd ~/SmartHome/PVService/bin/Debug/net6.0/linux-arm/publish/; ./PVService'
    - name: Start Charging Service
      run: |
        chmod +x ~/SmartHome/ChargingService/bin/Debug/net6.0/linux-arm/publish/ChargingService
        lxterminal -e 'cd ~/SmartHome/ChargingService/bin/Debug/net6.0/linux-arm/publish/; ./ChargingService'
    - name: Start Webapp
      run: |
        chmod +x ~/SmartHome/Smarthome.Web/bin/Debug/net6.0/linux-arm/publish/Smarthome.Web
        lxterminal -e 'cd ~/SmartHome/Smarthome.Web/bin/Debug/net6.0/linux-arm/publish/; ./Smarthome.Web'
