name: Build SmartHome.Web

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      solution: 'SmartHome.Web.sln'
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solution }} -r linux-arm
    - name: Build
      run: dotnet publish ${{ env.solution }} --no-restore -r linux-arm --self-contained false
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    
    
    - uses: actions/upload-artifact@master
      with:
        name: SmartHome.Web.artifacts
        path: |
          PVService/bin/Debug/net6.0/linux-arm/publish
          ChargingService/bin/Debug/net6.0/linux-arm/publish
          SensorDataService/bin/Debug/net6.0/linux-arm/publish
          Smarthome.Web/bin/Debug/net6.0/linux-arm/publish
  
  deploy:
    runs-on: [self-hosted]
    needs: build
    
    steps:
    - name: Stopping Services
      continue-on-error: true
      run: |
        pkill PVService
        pkill ChargingService
        pkill SensorDataService
        pkill Smarthome.Web
        
    - name: Removing old content
      continue-on-error: true
      run: |
        rm -rf ~/SmartHome/Smarthome.Web
        rm -rf ~/SmartHome/PVService
        rm -rf ~/SmartHome/ChargingService
        rm -rf ~/SmartHome/SensorDataService
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: SmartHome.Web.artifacts
        path: ~/SmartHome
        
    - name: Start PV Service
      run: |
        chmod +x ~/SmartHome/PVService/bin/Debug/net6.0/linux-arm/publish/PVService
        cd ~/SmartHome/PVService/bin/Debug/net6.0/linux-arm/publish/
        RUNNER_TRACKING_ID="" && gnome-terminal --tab -- ./PVService
    - name: Start Charging Service
      run: |
        chmod +x ~/SmartHome/ChargingService/bin/Debug/net6.0/linux-arm/publish/ChargingService
        cd ~/SmartHome/ChargingService/bin/Debug/net6.0/linux-arm/publish/
        RUNNER_TRACKING_ID="" && gnome-terminal --tab -- ./ChargingService
    - name: Start SensorDataController Service
      run: |
        chmod +x ~/SmartHome/SensorDataService/bin/Debug/net6.0/linux-arm/publish/SensorDataService
        cd ~/SmartHome/SensorDataService/bin/Debug/net6.0/linux-arm/publish/
        RUNNER_TRACKING_ID="" && gnome-terminal --tab -- ./SensorDataService
    - name: Start Webapp
      run: |
        chmod +x ~/SmartHome/Smarthome.Web/bin/Debug/net6.0/linux-arm/publish/Smarthome.Web
        cd ~/SmartHome/Smarthome.Web/bin/Debug/net6.0/linux-arm/publish/
        RUNNER_TRACKING_ID="" && gnome-terminal --tab -- ./Smarthome.Web
