name: Build SmartHome.Web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      solution: 'SmartHome.Web.sln'
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solution }}
    - name: Build
      run: dotnet build ${{ env.solution }} --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - uses: actions/upload-artifact@master
      with:
        name: SmartHome.Web.artifacts
        path: |
          PVService/bin/Debug/net6.0
          ChargingService/bin/Debug/net6.0
          Smarthome.Web/bin/Debug/net6.0
  
  deploy:
    runs-on: [self-hosted]
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: SmartHome.Web.artifacts
        path: ~/SmartHome
    
